### ISSUE TITLE
Why minihost remains opened with no running servers?

### ISSUE THREAD

**Issue by Alex0007** [typicode/minihost#3]

**Comment by typicode** [comment]
That's a good question. Short answer would be there's no good reason right now.
At some point, when there was no running servers, minihost would shutdown.

But I started thinking about 2 things:
- From a user point of view, would it be better to have a connection error when going to http://localhost:2000 or a message with something like 'No running servers, add one using h -- cmd'? (what's your opinion on that?)
- Minihost could as well proxy requests to ports and not process. For example, http://apache.127.0.0.1.xip.io could proxy to 80. So there would be no way for minihost to know if it should stop itself.

But since I'm not sure if the second feature would be that useful, maybe I'll implement back the "autostop" feature.

**Comment by typicode** [comment]
All in all, I agree that it's a half-done behaviour right now.

**Comment by typicode** [comment]
Just released `v0.3.8`.
Among the things I've changed, I've added back the autostop feature.

**Comment by Alex0007** [comment]
Seems like web-interface is broken now (with servers running)
![img](http://i.imgur.com/QHhoDwY.png)

**Comment by typicode** [comment]
Sorry about that, that's strange.
Can you access servers using http://<name>.127.0.0.1.xip.io:2000 ?
Could you stop running servers and minihost/proxy.js (you should be able to find it using `ps aux | grep node`)

Since previous version doesn't autostop, you may be still running the old version.

**Comment by Alex0007** [comment]
Old minihost process killing worked for me.
Autostop works nice

Good job, typicode!

**Comment by typicode** [comment]
Great! :)
