### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Alex0007** [typicode/minihost#6]
![img](http://i.imgur.com/5vCsqUy.png)
![img](http://i.imgur.com/3uEi3HM.png)
Server is not available by http://bb-composer-dev2.127.0.0.1.xip.io:2000/ , but available by localhost:port

It worked in v0.3.5 

OS: Linux

**Comment by typicode** [comment]
First, thanks for the feedback that's really helpful.

This issue is a bit strange and I don't really understand where the message Cannot GET/ is coming.

Basically, when you make a request to http://app.127.0.0.1.xip.io:2000, you should have 2 possible errors:

* app is not defined and you should get a 404 error Not found (you can try with http://foobar.127.0.0.1.xip.io:2000)
* app is not reachable and you should get a 502 error Error: connect ECONNREFUSED (you can try with h -- python -m SimpleHTTPServer, server won't be reachable because [PORT] wasn't set)

Does it happen sometimes or always?
Do you see bb-composer when going to localhost:2000?

If you can provide a failing test, that would be awesome.
I'm updating minihost to give more informations as well.

**Comment by typicode** [comment]
Also, you can find logs in `/tmp/minihost.log` maybe that coulp help.

**Comment by Alex0007** [comment]
Nothing strange in logs

> Do you see bb-composer when going to localhost:2000?

yes

Problem dissapeared after system reboot and now i can't reproduce it

**Comment by typicode** [comment]
> Problem dissapeared after system reboot and now i can't reproduce it

That's a good news at least :) If it appears again, feel free to reopen/create a new issue.

**Comment by Alex0007** [comment]
Starting minihost
```
h --n bb-composer-dev -- watchalive /tmp/watchem7.json
h --n bb-composer -- node-dev server/index.js
```

And then, bb-composer-dev url (http://bb-composer-dev.127.0.0.1.xip.io:2000/) for some reason points to bb-composer (and bb-composer points to bb-composer)

Clicking on IP of bb-composer-dev works normally

**Comment by typicode** [comment]
It should be good now.

Actually, it was the name detection that was buggy.
It was matching the first part of `bb-composer-dev` with `bb-composer' and stopped without checking for `bb-composer-dev`.

**Comment by Alex0007** [comment]
👍 👍
Fix confirmed
