### ISSUE TITLE
Stops to be resolved on widnows

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#8]
Sometimes while work of `h -name my-app ..`

Suddenly `http:/my-app.127.0.0.1.xip.io:2000/profile` becomes anavialble (not resolved), in chrome.

```
This webpage is not available

ERR_NAME_NOT_RESOLVED
```

in localhost:2000 - there is

```
my-app
localhost:58616
```

localhost:58616 is available

windows 7x64, node 0.12, minhost 0.3.12

is there way to debug or something?

**Comment by typicode** [comment]
minihost logs are written to `os.tmpdir() + /minihost.log`
Since, I'm not on Windows right now I can't say where it is. But if you can run this code:

```javascript
console.log(require('os').tmpdir())
```

You should be able to know.

I've googled `ERR_NAME_NOT_RESOLVED` seems to mean that the browser can't resolve the address.

I don't really know why you get that. Is it temporary? Do you have this error in other browsers at the same moment?

As a quick fix, you can use other domains that resolve to `127.0.0.1`:

```
http://my-app.til.io:2000
http://my-app.localtest.me:2000
...
```

It would be interesting to see if it happens with other domains too.

**Comment by whitecolor** [comment]
Chrome stops resolving, I go to opera - it too can not resolve, I go to firefox - it resolves! and then chrome starts resolsving - that what I noticed.

Thanks for suggestions.

**Comment by typicode** [comment]
Weird :/ And on Chrome when it doesn't resolve, does til.io resolves? I wonder if it's related to xip.io.
Also, it may be worth trying using Google Public DNS (8.8.8.8) and see if it happens too. That way, you could test if it's related to your Internet Access provider DNS.

**Comment by whitecolor** [comment]
Ok, I will check when it happens again, it's not very frequent.

**Comment by whitecolor** [comment]
Still continue to get different misbehaviours on windows (for example address stops to be available), have to to restart all intances. Is there an option to restart all (redo all the bindings)? Maybe worth to add it.

**Comment by typicode** [comment]
Do you mean you still have `ERR_NAME_NOT_RESOLVED` or simply servers are not listed anymore on `localhost:2000` and you get a `404` error when you try to access an instance?

**Comment by whitecolor** [comment]
Well maybe the problem with dnsCrypt disabled it, will report the result.

**Comment by whitecolor** [comment]
it seems to be solve by using `.dev` domain instead of `127.0.0.1.xpi.io`. I will close when ensure that everything is ok.
