### ISSUE TITLE
Name continues to be resolved after shut down (incorrectly)

### ISSUE THREAD

**Issue by whitecolor** [typicode/minihost#9]
Real case, I have two servers started:

localhost: 2000 shows:

```
bb-reader
localhost:62547

bb-reader-dev
localhost:62546
```

When `bb-reader-dev` shuts down (only `bb-reader` in the list)

http://bb-reader-dev.127.0.0.1.til.io:2000/ continues to be available and opens `bb-reader` host.

Windows 7x64, node 0.12.2

**Comment by typicode** [comment]
Thanks for the issue and sorry for the late reply.

I think it's due to the fact that `bb-reader` is matching part of http://bb-reader-dev.127.0.0.1.til.io:2000/
I've changed the way the proxy work to look only for `bb-reader.` in the URL instead of `bb-reader`

I hope it'll definitely solve this name problem.

BTW, I'm working also on [hotel](https://github.com/typicode/hotel), if you want to give a try. It doesn't use external services like xip.io, so you won't have DNS problems at least.

**Comment by whitecolor** [comment]
Won't minihost and hotel conflict as they both start their UI on http://localhost:2000/ ?

**Comment by typicode** [comment]
You're welcome.
You're right. You can set a different port for each one (for example `2000̀` for minihost and `2500̀` for hotel).
For `hotel`, go to `%HOMEPATH%/.hotel/conf.json` then run `hotel stop && hotel start`.
